name: hesabdar
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.1
  # persian_datetime_picker: ^2.6.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  persian_datetime_picker:
    git:
      url: https://github.com/mrsaeedi/persian-datetime-picker.git
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.3
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#75e6e0"
  color_dark: "#75e6e0"
  image: assets/images/fullsize.png
  image_dark: assets/images/fullsize.png
  android_gravity: fill
  android: true
  ios: true
android_12:
  image: assets/images/fullsize.png
  icon_background_color: "#ffffff"
  image_dark: assets/images/fullsize.png
  icon_background_color_dark: "#75e6e0"
  splash_screen_image_scale: 2

  web: false



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/vazer/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/vazer/Vazir-Bold.ttf
          weight: 700
        - asset: assets/vazer/Vazir-Light.ttf
          weight: 300
        - asset: assets/vazer/Vazir-Medium.ttf
          weight: 500
        - asset: assets/vazer/Vazir-Thin.ttf
          weight: 100
        - asset: assets/vazer/Vazir.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
